OLX/OLX/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('olxapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OLX/olxapp/urls.py
from django.contrib import admin
from django.urls import path
from olxapp import views
app_name='olxapp'

urlpatterns = [
    path('',views.home,name='view'),
    path('details/<int:pk>',views.detail.as_view(),name='details'),
    path('delete/<int:pk>',views.delete.as_view(),name='delete'),
    path('edit/<int:pk>/',views.update.as_view(),name='edit'),
    path('add/',views.Add,name='add'),
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
]

OLX/olxapp/models.py
from django.db import models

class product(models.Model):
    product_name=models.CharField(max_length=40)
    price=models.IntegerField()
    year_reg = models.CharField(max_length=20)
    product_image=models.ImageField(upload_to='media',null=True,blank=True)
    posted_time=models.DateTimeField(auto_now_add=True)
    product_desc=models.TextField()

    def __str__(self):
        return self.product_name

# class user(models.Model):
#     name=models.CharField(max_length=30)
#     place=models.CharField(max_length=40)
#     phone=models.IntegerField(default=0)
#     def __str__(self):
#         return self.name

OLX/olxapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import product
from django.views.generic import DetailView,DeleteView,UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

def home(request):
    b=product.objects.all()
    return render(request,'view.html',{'b':b})
# def detail(request,n):
#     b=product.objects.all(id=n)
#     return render(request, 'view.html', {'b': b})


class detail(DetailView):
    model=product
    template_name="detail.html"
    context_object_name="b"

# def delete(request,n):
#     b=product.objects.get(id=n)
#     b.delete()
#     return home(request)

class delete(DeleteView):
    model=product
    template_name='delete.html'
    success_url = reverse_lazy('olxapp:view')

class update(UpdateView):
    model=product
    template_name='edit.html'
    fields = ['product_name','price','product_desc','year_reg','product_image',]
    success_url = reverse_lazy('olxapp:view')

@login_required
def Add(request):
    if(request.method=='POST'):
        a=request.POST['a']
        b=request.POST['b']
        c=request.POST['c']
        d=request.FILES['d']
        e=request.POST['e']

        p=product.objects.create(product_name=a,price=b,year_reg=c,product_image=d,product_desc=e)
        p.save()
        return home(request)
    return render(request,'add.html')


def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        c=request.POST['c']
        e=request.POST['e']
        f=request.POST['f']
        l=request.POST['l']
        if(c==p):
          b=User.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l)
          b.save()
          return redirect('olxapp:view')
        else:
            return HttpResponse("Passwords are not same")
    return render (request,'register.html')

def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('olxapp:view')
        else:
            return HttpResponse('Invalid Credentials')
    return render(request,'login.html')

@login_required
def user_logout(request):
    logout(request)
    return user_login(request)

OLX/templates/Add.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<br>
<h1 class="text-center">Add product</h1>

<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Product Name</label>
    <input type="text" class="form-control" name="a">
  <div class="mb-3">
    <label class="form-label">Price</label>
    <input type="text" class="form-control" name="b">
  </div>
   <div class="mb-3">
    <label  class="form-label">Year Of Registration</label>
    <input type="text" class="form-control" name="c">
  </div>
     <div class="mb-3">
    <label  class="form-label">Product Image</label>
    <input type="file" class="form-control" name="d">
  </div>
   <div class="mb-3">
    <label  class="form-label">Product Description</label>
    <input type="text" class="form-control" name="e">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

OLX/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand text-success fw-bold fst-italic" href="#">OLX</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'olxapp:view'  %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'olxapp:add'  %}">Add</a>
        </li>
         <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'olxapp:logout' %}">logout</a>
        </li>
        {% else %}
         <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'olxapp:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'olxapp:login' %}">login</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

OLX/templates/delete.html
<!DOCTYPE html>
{% extends 'base.html' %}
{%load static%}
{% block title%}
Movie page
{% endblock %}
{% block content %}
<h1 class="text-center">Delete Movie</h1>
<form method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    <table>
{{form.as_table}}
</table>
    <p>Are you sure you want to delete???..</p>
    <input type="submit">
    </form>

{%endblock%}

OLX/templates/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row mt-4 ms-5">
        <div class="col-md-6 ">
            <img src="{{b.product_image.url}}" height="400px" width="90%" style="border-radius:10px;">
        </div>
        <div class="col-md-6">
            <h3 class="fw-bold">{{b.product_name}}</h3>
            <p><i>{{b.price}}</i></p>
            <p><i>{{b.year_reg}}</i></p>
            <p>{{b.product_desc}}</p>
            <a href="{% url 'olxapp:edit' b.id %}" class="btn btn-info">UPDATE</a>
            <a  class="btn btn-danger" href="{% url 'olxapp:delete' b.id %}">DELETE</a>
        </div>
    </div>
</div>
{% endblock %}

OLX/templates/edit.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
edit page
{% endblock %}
{% block content %}
<form method="POST"  enctype="multipart/form-data">
    {%csrf_token%}

  {{form}}
    <input type="submit">
</form>
{% endblock %}

OLX/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<br>
<h1>Login Page</h1>
<form method="POST">
    {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u">
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p">
  </div>
      <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

OLX/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<br>
<h1>Register page</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u">
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p">
  </div>
   <div class="mb-3">
    <label  class="form-label">Confirm Password</label>
    <input type="password" class="form-control" name="c">
  </div>
     <div class="mb-3">
    <label  class="form-label">E-mail</label>
    <input type="email" class="form-control" name="e">
  </div>
   <div class="mb-3">
    <label  class="form-label">First Name</label>
    <input type="text" class="form-control" name="f">
  </div>
   <div class="mb-3">
    <label  class="form-label">Last Name</label>
    <input type="text" class="form-control" name="l">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<br>
<br>
<br>
{% endblock %}

OLX/templates/view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="mt-2">
    <div class="container">
        <div class="row">

           {% for i in b %}
            <div class="col-md-3">
             <div class="card" style="width: 17rem;height:500px;border-radius:12px;">
           <img src="{{i.product_image.url}}" class="card-img-top" style="height:350px;width:100%;border-radius:12px;">
           <div class="card-body">
          <h5 class="card-title">{{i.product_name}}</h5>
          <p>Price : ₹{{i.price}}</p>
         <p class="card-text">{{i.year_reg}}</p>
          <p>Posted time : {{i.posted_time }}</p>
          <a href="{% url 'olxapp:details' i.id %}" class="btn btn-primary">More Details</a>
         </div>
         </div>
         </div>
            {% endfor %}
        </div>
    </div>
</section>
{%endblock%}